#Playing with the kubernetes module to see what patch management looks like
---
- name: Patch a Kubernetes cluster using Ansible
  hosts: localhost
  tasks:
    - name: Check the current version of the cluster
      k8s:
        api_version: v1
        kind: Version
        namespace: default
        name: kube-version
        state: present
        register: version

    - name: Upgrade the cluster to the latest version
      k8s:
        api_version: v1
        kind: Version
        namespace: default
        name: kube-version
        state: patched
        patch: '{"spec": {"desiredUpdate": {"version": "{{ version.resources[0].status.currentVersion }}"}}}'
